name: Snowflake Extension Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-snowflake-extension:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential ninja-build
        
    - name: Build DuckDB with Snowflake Extension
      run: |
        cd duckdb
        make debug
        
    - name: Build Snowflake Extension
      run: |
        cd build/debug
        ninja
        
    - name: Run Snowflake Basic Connectivity Tests
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      run: |
        cd build/debug
        ./test/unittest "/home/runner/work/test1/test1/test/sql/snowflake_basic_connectivity.test"
        
    - name: Run Snowflake Pushdown Proof Tests
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      run: |
        cd build/debug
        ./test/unittest "/home/runner/work/test1/test1/test/sql/snowflake_pushdown_proof.test"
        
    - name: Run All Snowflake Tests
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      run: |
        cd build/debug
        ./test/unittest "[sql]" --list-tests | grep snowflake | while read test; do
          echo "Running test: $test"
          ./test/unittest "$test" || echo "Test failed: $test"
        done
