name: Snowflake SQL Logic Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-snowflake-extension:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential ninja-build
        
    - name: Build DuckDB with Snowflake Extension
      run: |
        cd duckdb
        make debug
        
    - name: Run Snowflake SQL Logic Tests
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      run: |
        cd duckdb
        ./build/debug/test/unittest "/home/runner/work/duckdb-snowflake/duckdb-snowflake/test/sql/snowflake_pushdown_proof.test"
        ./build/debug/test/unittest "/home/runner/work/duckdb-snowflake/duckdb-snowflake/test/sql/snowflake_basic_connectivity.test"
        
    - name: Run All Snowflake Tests
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      run: |
        cd duckdb
        ./build/debug/test/unittest "[sql]" --list-tests | grep snowflake
        echo "Running all Snowflake tests..."
        ./build/debug/test/unittest "[sql]" | grep -E "(snowflake|PASSED|FAILED)"
